proje/Models/ErrorViewModel.cs
namespace proje.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

proje/Controllers/AwardController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Classes;
using Service.ViewModels;

namespace proje.Controllers
{
    public class AwardController : Controller
    {
        private AwardService awardService;
        public AwardController()
        {
            awardService = new AwardService();
        }
        public IActionResult Index(int filmid)
        { 
            var vm = awardService.GetAwardsVM(filmid);
            return View(vm);
        }


        public IActionResult Create(int filmid)
        {
            var vm = awardService.getAwardsCE_VM(filmid);
            return View(vm);
        }
        [HttpPost]
        public IActionResult Create(AwardsCE_VM vm)
        {
            awardService.AddAdwar(vm);
            return RedirectToAction("Index","Film");
        }
    }
}

proje/Controllers/FilmController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Classes;
using Service.ViewModels;

namespace proje.Controllers
{
    public class FilmController : Base
    {
        private FilmService filmService;
        public FilmController()
        {
            filmService = new FilmService();
        }
        public IActionResult Index()
        {

            FilmService filmService = new FilmService();
            var list = filmService.GetFilms();
            return View(list);

        }
        
        
        public IActionResult Create()
        {
            var vm = filmService.getFilmCE_VM();
            return View(vm);
        }
        [HttpPost]
        public IActionResult Create(FilmVM vm)
        {
            filmService.AddFilm(vm);
            return RedirectToAction("Index");
        }

        
        public IActionResult Delete(int id)
        {
           var result=filmService.DeleteFilm(id);
            if (result == false)
                ViewData["message"] = "no";
            else
                ViewData["message"] = "yes";
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id )
        {
            var vm = filmService.getFilmEdit_VM(id);
            return View(vm);
        }
        [HttpPost]
        public IActionResult Edit(FilmVM vm)
        {
            filmService.EditFilm(vm);
            return RedirectToAction("Index");
        }

    }
}

proje/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using proje.Models;

using Service.Models;
using System.Diagnostics;

namespace proje.Controllers
{
    public class HomeController : Base
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()

        {
            return View();
        }

        public IActionResult Privacy()

        {
            return View();

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    } 
}

proje/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using Service.Classes;
using Service.ViewModels;
using Service.Models;


namespace proje.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Hoşgeldiniz";
            return View();
        }

        [HttpPost]

        public IActionResult Index(RegisterVM vm)
        {
            ViewBag.Title = "Welcome";
            Authentication cslAuth = new Authentication();


            if (cslAuth.UsernamePasswordControl(vm.Email, vm.Paswordd))
            {
                ViewBag.Mesaj = "giriş başarılı TEBRİKLER";
                HttpContext.Session.SetString("UserSession", "1");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Mesaj = cslAuth.ErrorMessage;
            }
            return View();

        }
    }
}

proje/Views/Award/Create.cshtml
@model Service.ViewModels.AwardsCE_VM
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Awards</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input asp-for="Filmid" hidden value="@Model.Filmid"  />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Awardname" class="control-label"></label>
                <input asp-for="Awardname" class="form-control" />
                <span asp-validation-for="Awardname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
           
               
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

proje/Views/Award/Index.cshtml
@model Service.ViewModels.AwardsVM

@{
    ViewData["Title"] = "Index";
}
<h1>@Model.Name~Awards </h1>
<div>
    @if (TempData["message"] != null)
    {
        @TempData["message"].ToString() @* silindi silinmedi mesajı verir*@
    }

</div>


<p>
    <a asp-action="Create" asp-route-Filmid="@Model.Filmid">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Award Name
            </th>
            <th>
                Year
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AwardsListItem)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Awardname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
 
               
            </tr>
        }
    </tbody>
</table>

proje/Views/Film/Create.cshtml
@model Service.ViewModels.FilmCE_VM
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imdb" class="control-label"></label>
                <input asp-for="Imdb" class="form-control" />
                <span asp-validation-for="Imdb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" accept="image/*" />
                <span asp-validation-for="Image" class="text-danger"></span>

            </div>
            <div class="form-group">
            <label asp-for="Comment" class="control-label"></label>
            <input asp-for="Comment" class="form-control" />
            <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genreid" class="control-label"></label>
                <select asp-for="Genreid" asp-items="@(new SelectList(Model.GenreList,"Id","GenreName"))" class="form-control">
                    <option>Seçiniz</option>
                </select>
                
                <span asp-validation-for="Genreid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

proje/Views/Film/Edit.cshtml
@model Service.ViewModels.FilmCE_VM
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imdb" class="control-label"></label>
                <input asp-for="Imdb" class="form-control" />
                <span asp-validation-for="Imdb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" type="file" accept="image/*" />
                <span asp-validation-for="Image" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genreid" class="control-label"></label>
                <select asp-for="Genreid" asp-items="@(new SelectList(Model.GenreList,"Id","GenreName"))" class="form-control">
                    <option>Seçiniz</option>
                </select>

                <span asp-validation-for="Genreid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

proje/Views/Film/Index.cshtml
@model IEnumerable<Service.ViewModels.FilmVM>

@{
    ViewData["Title"] = "Index";
}
<div>
    @if (TempData["message"] != null)
    {
        @TempData["message"].ToString() @* silindi silinmedi mesajı verir*@
    }
    
</div>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imdb)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GenreName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imdb)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GenreName)
                </td>
                <td>
                    <img style="width:100%;height:150px" src="/image/@item.Image" class="card-img-top" alt="...">
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    <a asp-action="Index" asp-controller="Award" asp-route-filmid="@item.Id">Awards</a>
                </td>
            </tr>
        }
    </tbody>
</table>

proje/Views/Register/Index.cshtml
@model Service.ViewModels.RegisterVM

<h2> Giriş Yapınız</h2>
<p style="background-color:red;">@TempData["error"]</p>
<hr />


<form asp-controller="Register" asp-action="Index" method="post">

    <div class="form-group">
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "KullaniciAdi",required="required"  })
        @Html.ValidationMessageFor(model => model.Email)
    </div>

    <div class="form-group">
        @Html.PasswordFor(model => model.Paswordd, new { @class = "form-control", @placeholder = "Şifre",required="required"  })
        @Html.ValidationMessageFor(model => model.Paswordd)
    </div>

    <div class="form-group">
        <p class="submit"><input type="submit" name="commit" value="Giriş"></p>
    </div>


</form>

proje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - proje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/proje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Film" asp-action="Index">B.T. MOVİE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Index">Films</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Create">Film Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/css/boostrap.min.css"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>